name: CI/CD Laravel Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-scripts --no-progress

     
      - name: Setup environment
        run: cp .env.example .env

      - name: Generate Laravel key
        run: php artisan key:generate

      
      - name: Run tests
        run: php artisan test

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

     
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            carloshipoldev/alpesone-api:latest
            carloshipoldev/alpesone-api:${{ github.sha }}